### ISSUE TITLE
Currying up to 9 arguments

### ISSUE THREAD

**Issue by draptik** [la-yumba/functional-csharp-code#13]
I enjoy using LaYumba for teaching.

Anybody interested in Currying up to 9 arguments?

Reason I'm asking: in a previous course (using LaYumba) it took me some time to figure out why the students code wasn't working:  ...the student used `Apply` for a function with more than 3 arguments...;-)

Currently, currying only supports 3 arguments. 

Would a pull request be of interest to other people?

**Comment by la-yumba** [comment]
I would accept a PR if it makes the library more useful to some (as long as everything is nice and clean and consistent :-)

**Comment by draptik** [comment]
If the `Apply` PR is ok, I could also do this for `Map`.

**Comment by draptik** [comment]
@la-yumba would you mind publishing a minor release this week including this minor extension (`Apply`)? I'm giving a workshop & talk next week. And, of course I will be promoting your book! ;-)

**Comment by la-yumba** [comment]
@draptik done (should be indexed shortly). Please have a check (haven't done this in a while ;-)
