### ISSUE TITLE
Unpon fresh clone, the solution does not build

### ISSUE THREAD

**Issue by gentledepp** [la-yumba/functional-csharp-code#20]
# Problem
I just cloned the repository and tried to build.
VS 2019 gives me the following error:
![image](https://user-images.githubusercontent.com/1175751/138227209-97b17220-8c2f-4810-a889-a316bc02b811.png)

Running `dotnet restore` then reveals the real issue (sorry - German)
![image](https://user-images.githubusercontent.com/1175751/138227322-b8d45a9b-ae5c-4dfc-9416-ef5f7468662b.png)

The index for the source "https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" cannot be loaded - the SSL connection could not be established. It seems the remote certificate is invalid.

# Solution
This can easily be fixed by running
`dotnet restore --ignore-failed-sources`

Thereafter the build succeeds.

You may still want to 
1. either fix this or (what do you need the myget repo for?)
2. inform new users of this repo by providing a hint in the readme.md

What do you prefer?

**Comment by la-yumba** [comment]
I think this issue is not specific to my repo, but perhaps has to do with the configuration of your system vs .NET 6 requirements. Try googling, and creating a simple .NET 6 project of your own.
