### ISSUE TITLE
.NET Core 2.0 support

### ISSUE THREAD

**Issue by hpcsc** [la-yumba/functional-csharp-code#3]
Hi,

Is it possible to upgrade the project to support .NET Core 2.0? There are quite a lot of changes from 1.1 to 2.0, especially migration from project.json to msbuild. Most of people should use 2.0 now

And thanks for the awesome book. I really enjoy reading it

**Comment by la-yumba** [comment]
.NET Core 1.1 uses msbuild and does not use project.json files (which were obsolete and have now been removed)

On the other hand, it would make sense to migrate the executables to .NET Core 2, but this is not my priority right now. I'd be happy to look at PRs - README should also be updated, and it should work from both VS and the CLI.

**Comment by hpcsc** [comment]
sorry, my mistake. I saw a lot of project.json and thought they were still using project.json approach. 

I created the PR to migrate executables to .NET Core 2, please help to review
