### ISSUE TITLE
Code errors 

### ISSUE THREAD

**Issue by lctk** [la-yumba/functional-csharp-code#8]
In Chapter 10, the code is
`var startOfPeriod = new DateTime(year, month, 1);
         var endOfPeriod = startOfPeriod.AddMonths(1);

         var eventsBeforePeriod = events
            .TakeWhile(e => e.Timestamp < startOfPeriod);
         var eventsDuringPeriod = events
            .SkipWhile(e => e.Timestamp < startOfPeriod)
            .TakeWhile(e => endOfPeriod < e.Timestamp);`

I think the correct code should be
`var eventsDuringPeriod = events
            .SkipWhile(e => e.Timestamp < startOfPeriod)
            .TakeWhile(e => e.Timestamp < endOfPeriod  );`

**Comment by la-yumba** [comment]
yes, that's correct
