### ISSUE TITLE
no chapter 8 exercise solutions

### ISSUE THREAD

**Issue by jwilliamson1** [la-yumba/functional-csharp-code#9]
stuck on chapter 8 exercises. can you post solutions?

**Comment by garethhubball** [comment]
This chapter has been one of the sticking points for me so I would love to see the canonical solutions.

**Comment by la-yumba** [comment]
Hi, sorry for the late reply. This has been addressed in commit 5b87d66. 
In case you're interested, the [code for the 2nd edition](https://github.com/la-yumba/functional-csharp-code-2) (which itself is in [MEAP](https://www.manning.com/books/functional-programming-in-c-sharp-second-edition)) is available
